- name: Reset Redis module
  ansible.builtin.command: dnf module reset redis -y

- name: enable redis remi - 6.2
  ansible.builtin.shell: dnf module enable redis:6 -y


- name: install redis remi release
  ansible.builtin.dnf:
    name: redis
    state: present

- name: Update listen address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start and enable redis
  ansible.builtin.service:
    name: redis
    state: restarted
    enabled: true
      
