- name: "App Setup {{component}}"
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: Install Java
  ansible.builtin.import_role:
    name: common
    tasks_from: java 


- name: Mysql Setup 
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql-setup

- name: System {{component}} Start Service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd
