- name: "App Setup {{component}}"
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup


- name: Install Python 
  ansible.builtin.import_role:
    name: common
    tasks_from: python 

- name: "{{component}} start service"
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd
