- name: configure yum repos vendor
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash


- name: configure yum repo for rabbitmq
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: install rabbitmq
  ansible.builtin.dnf:
    name: rabbitmq-server 

- name: start and enable rabbitmq service
  ansible.builtin.service:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: create a user to access rabbitmq-server
  ansible.builtin.command: "rabbitmqctl add_user {{rq_user}} {{rq_password}}"


- name: set permisiions for user
  ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"