- name: disable mysql
  ansible.builtin.shell:  dnf module disable mysql -y

- name: copy mysql repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: install mysql
  ansible.builtin.package:
    name: mysql-community-server
    state: present

- name: Start Mysql Service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: change default root password
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ lookup('aws_ssm', '/roboshop/{{env}}/}/mysql_root_password', region='us-east-1', decrypt=True ) }}"