- name: "{{component}} APP Setup"
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup


- name: Install Golang
  ansible.builtin.import_role:
    name: common
    tasks_from: go 

- name: "{{component}} service start"
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd