- name: Install Nginx server
  ansible.builtin.dnf:
    name: nginx 
    state: present

- name: remove default content of nginx home page
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent 

- name: remove default content of nginx home page
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download web Application
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/web.zip
    dest: /tmp

- name: Extract Application
  ansible.builtin.unarchive:
    src: /tmp/web.zip
    dest: /usr/share/nginx/html
    remote_src: yes


- name: copy roboshop configuration
  ansible.builtin.template:
    src: roboshop.conf.j2
    dest: /etc/nginx/default.d/roboshop.conf
  notify:
    - Restart Nginx