- name: create application user = roboshop
  ansible.builtin.user:
    name: roboshop

- name: recursively delete directory
  ansible.builtin.file:
    path: /app
    state: absent
    

- name: create a directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download shipping {{component}}.zip file
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/shipping.zip
    dest: /tmp
  when: component == "shipping"

- name: Download {{component}}.zip file
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/{{component}}.zip
    dest: /tmp
  when: component != "shipping"



- name: Extract {{component}}.zip file
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: yes