- name: Copy mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: install MongoDB from the repo
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present

- name: Fetch the categories count
  ansible.builtin.command: mongo --host mongodb.learndevopswithprakash.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: product_count
  when: component == "catalogue"

- name: Fetch the categories count
  ansible.builtin.command: mongo --host mongodb.learndevopswithprakash.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
  register: user_count
  when: component == "user"


- name: Load catalogue data into mongodb server
  ansible.builtin.shell: mongo --host mongodb.learndevopswithprakash.online < /app/schema/catalogue.js
  when: component == "catalogue" and product_count.stdout == "0" 

- name: Load user data into mongodb server
  ansible.builtin.shell: mongo --host mongodb.learndevopswithprakash.online < /app/schema/user.js
  when: component == "user" and user_count.stdout == "0" 

