- name: install mysql
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: check if schema exists or not
  ansible.builtin.command: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
  register: schema

- name: print schema
  ansible.builtin.debug:
    msg: "SCHEMA: {{schema}}"

- name: load schema to mysql
  ansible.builtin.shell: "mysql -h mysql.learndevopswithprakash.online -uroot -p{{mysql_password}} < /app/schema/shipping.sql"
  when: schema.stdout != "1"
