- name: disable current nodejs and enable nodejs 18 
  ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y


- name: install nodejs 18
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: npm instal dependencies 
  ansible.builtin.command: npm install
  args:
    chdir: /app
