- name: install python 3.6
  ansible.builtin.dnf:
    name: "{{item}}"
    state: present
  loop:
  - python36
  - gcc 
  - python3-devel


- name: install pip package from requirement.txt
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args: 
    chdir: /app