- name: Application Setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: Install Node-JS 
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs 


- name: System Start service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd
